### ISSUE TITLE
Link tags and other content-free tags are awkward

### ISSUE THREAD

**Issue by knewter** [zambal/eml#1]
Presently, as far as I can tell, this is the only way to generate a link tag for a stylesheet:

```elixir
link [rel: "stylesheet", type: "text/css", href: "/public/base.css"], ""
```

It's kind of awkward looking.  Did I overlook something, or is this actually what you have to do presently?  BTW really enjoying Eml and am presently doing an ElixirSip using it :)

**Comment by zambal** [comment]
Hi, I just released a new version of Eml. I have deceided to prioritize attributes syntax above content syntax. So now you can write

eml do
  div id: "test"
end

However, if you want to define an element without attributes, you now need to write:

eml do
  div [], "content"
end

I'm still not sure about supporting both content and attributes as the first argument for the same reasons as I wrote in my previous reply.

**Comment by mjs2600** [comment]
Why not put content in a do block like this:
```elixir
eml do
  div do
    "content"
  end
end
```

it also make it easier to nest things:

```elixir
eml do
  div id: "test" do
    span do
      "content"
    end
  end
end
```

**Comment by zambal** [comment]
Ah, I forgot to tell that this is actually possible in the current version. Also, the attributes keyword list gets converted to a map, so this is all valid in the current version of Eml:

```elixir
eml do
  html do
    head do
      meta charset: "UTF-8"
    end
    body %{lang: "en"} do
      h1 do
        "Hello World!"
      end
      div [class: "test"], "blah blah"
      div %{id: "myid"}, "more blah blah"
      div class: "test" do
        "lots and lots"
        " of text."
      end
    end
  end
end
```
